spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/HW1db
      username: root
      password: root





#mybatis-plus-configuration
mybatis-plus:
  global-config:
    db-config:
      table-prefix: "tbl_"
      id-type: ASSIGN_ID
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
