

server:
  port: ${SERVER_PORT:8080}
#aws:
#  accessKeyId: ${AWS_ACCESS_KEY_ID:root}
#  secretKey: ${AWS_SECRET_ACCESS_KEY:root}

spring:
  datasource:
      name: test
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:csye6225}/HW1db?createDatabaseIfNotExist=true

      url: jdbc:mysql://${DB_HOST}/${DB_NAME:csye6225}?createDatabaseIfNotExist=true
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
#      username: root
#      password: root




mybatis-plus:
  global-config:
    db-config:
      table-prefix: "tbl_"
      id-type: ASSIGN_ID
  mapper-locations: classpath*:/mapper/**/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
mybatis:
  table:
    auto: update
  model:
    pack: com.csye6225HW1.POJO
  database:
    type: mysql

      #扫描用于创建表的对象的包名

    #Amazon#2023





#mybatis-plus-configuration
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: "tbl_"
#      id-type: ASSIGN_ID
#  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml,classpath*:mapper/*/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





